# Generated by Django 4.2 on 2023-05-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Listings", new_name="Listing",),
    ]
