# Generated by Django 4.2 on 2023-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_rename_listings_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(default="", upload_to=""),
            preserve_default=False,
        ),
    ]
